mindful_bookshelf/bookshelf/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("books/", views.book_list, name="book_list"),
    path("about/", views.about, name="about"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup_view, name="signup"),  # Ensure correct URL mapping
    path("admin/overview/", views.admin_overview, name="admin_overview"),
    path(
        "admin/overview/delete_user/<int:user_id>/",
        views.delete_user,
        name="delete_user",
    ),
    path("add_book/", views.add_book, name="add_book"),
    path("add_category/", views.add_category, name="add_category"),
    path("book_detail/<int:book_id>/", views.book_detail, name="book_detail"),
    path("delete_book/", views.delete_book, name="delete_book"),
    path("edit/<int:book_id>/", views.edit_book_view, name="edit_book"),
    path("user-details/", views.user_details, name="user_details"),
    path(
        "toggle-book-availability/",
        views.toggle_book_availability,
        name="toggle_book_availability",
    ),
]

mindful_bookshelf/mindful_bookshelf/urls.py
from django.contrib import admin
from django.urls import path, include
from bookshelf import views

urlpatterns = [
    path("admin/", admin.site.urls),  # Admin URL pattern
    path("", views.book_list, name="home"),  # Redirect root URL to book list view
    path(
        "bookshelf/", include("bookshelf.urls")
    ),  # Include URL patterns from the bookshelf app
    # Add more URL patterns as needed
]

mindful_bookshelf/bookshelf/models.py
# bookshelf/models.py


from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseNotAllowed
from django import forms


# Define your Category model
class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


# Define your Book model
class Book(models.Model):
    title = models.CharField(max_length=100, unique=True)
    author = models.CharField(max_length=100)
    description = models.TextField()
    publication_date = models.DateField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    cover_image = models.ImageField(
        upload_to="static/bookshelf/book/img/", blank=True, null=True
    )
    pdf_document = models.FileField(
        upload_to="static/bookshelf/books/pdf/", blank=True, null=True
    )

    def __str__(self):
        return self.title


# Define your ReadingStatus model
class ReadingStatus(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    read = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username} - {self.book.title} - {'Read' if self.read else 'Unread'}"


# Define your ReadingHistory model
class ReadingHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    read_date = models.DateField()

    def __str__(self):
        return f"{self.user.username} - {self.book.title} - {self.read_date}"


# Define your BookForm
class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"


# Define a view function to edit a book
def edit_book_view(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    if request.method == "POST":
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            return redirect("book_detail", book_id=book_id)
    else:
        form = BookForm(instance=book)
    return render(request, "bookshelf/edit_book.html", {"form": form, "book": book})


# Define a view function to provide a book list view
def book_list(request):
    books = Book.objects.all()
    return render(request, "bookshelf/book_list.html", {"books": books})


# Define a view function to provide a book detail view
def book_detail(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    return render(request, "bookshelf/book_detail.html", {"book": book})


# Define a view function to mark a book as read
def mark_book_as_read(request, book_id):
    if request.method == "POST":
        user = request.user
        book = get_object_or_404(Book, id=book_id)
        reading_status, created = ReadingStatus.objects.get_or_create(
            user=user, book=book
        )
        reading_status.read = True
        reading_status.save()
        return redirect("book_detail", book_id=book_id)
    else:
        return HttpResponseNotAllowed(["POST"])

mindful_bookshelf/bookshelf/forms.py
# bookshelf/forms.py


from django import forms
from .models import Book, Category


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            "name",
            "description",
        ]

mindful_bookshelf/bookshelf/views.py
# bookshelf/views.py

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseForbidden
from .models import Book
from .forms import BookForm
from .forms import CategoryForm
from .models import Category
from django.contrib import messages


def book_list(request):
    books = Book.objects.all()
    return render(request, "bookshelf/book_list.html", {"books": books})


def book_detail(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    return render(request, "bookshelf/book_detail.html", {"book": book})


def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(
                "home"
            )  # Redirect to homepage after successful registration
        else:
            # Handle invalid form data (error messages, etc.)
            pass
    else:
        form = UserCreationForm()
    return render(request, "bookshelf/signup.html", {"form": form})


def login_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("home")
        else:
            return render(
                request,
                "bookshelf/login.html",
                {"error_message": "Invalid username or password"},
            )
    else:
        return render(request, "bookshelf/login.html")


@login_required
def logout_view(request):
    logout(request)
    return redirect("home")


def admin_overview(request):
    if request.method == "POST":
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("admin_overview")
    else:
        form = BookForm()

    # Query for books, users, and categories
    books = Book.objects.all()
    users = User.objects.exclude(is_superuser=True)
    categories = Category.objects.all()  # Query for categories

    # Pass data to the template
    context = {
        "form": form,
        "books": books,
        "users": users,
        "categories": categories,
        # Add book_id for each book
        "book_details": [{"book": book, "book_id": book.id} for book in books],
    }

    return render(request, "bookshelf/admin_overview.html", context)


def delete_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    if request.method == "POST":
        book.delete()
        return redirect("admin_overview")
    return redirect("admin_overview")


@user_passes_test(lambda u: u.is_superuser)
def delete_user(request, user_id):
    if user_id != request.user.id:
        try:
            user_to_delete = User.objects.get(pk=user_id)
            user_to_delete.delete()
            return redirect("admin_overview")
        except User.DoesNotExist:
            # Handle case where user doesn't exist
            return render(
                request, "bookshelf/error.html", {"message": "User not found"}
            )
    else:
        return HttpResponseForbidden("You cannot delete yourself.")


def user_details(request):
    if request.method == "GET":
        user_id = request.GET.get("id")
        user = User.objects.filter(id=user_id).first()
        if user:
            return render(request, "bookshelf/user_details.html", {"user": user})
        else:
            return render(request, "user_not_found.html")
    else:
        return HttpResponseNotAllowed(["GET"])


def add_book(request):
    if request.method == "POST":
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("book_list")  # Redirect to book list page after adding book
    else:
        form = BookForm()
    return render(request, "bookshelf/add_book.html", {"form": form})


def add_category(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("admin_overview")
        else:
            print(form.errors)  # Print form errors for debugging
    else:
        form = CategoryForm()

    return render(request, "bookshelf/add_category.html", {"form": form})


# Define a view function to edit a book
def edit_book_view(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    if request.method == "POST":
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            return redirect("book_detail", book_id=book_id)
    else:
        form = BookForm(instance=book)
    return render(request, "bookshelf/edit_book.html", {"form": form, "book": book})


# Define a view function to provide a book detail view
def book_detail(request, book_id=None):
    if book_id:
        book = get_object_or_404(Book, id=book_id)
    else:
        # Handle case where no book_id is provided (optional)
        book = None
    return render(request, "bookshelf/book_detail.html", {"book": book})


# Define a view function to mark a book as read
def mark_book_as_read(request, book_id):
    if request.method == "POST":
        user = request.user
        book = get_object_or_404(Book, id=book_id)
        reading_status, created = ReadingStatus.objects.get_or_create(
            user=user, book=book
        )
        reading_status.read = True
        reading_status.save()
        return redirect("book_detail", book_id=book_id)
    else:
        return HttpResponseNotAllowed(["POST"])


def toggle_book_availability(request):
    if request.method == "POST":
        book_id = request.POST.get("book_id")
        if book_id:
            try:
                book = Book.objects.get(pk=book_id)
                book.available = not book.available
                book.save()
                return JsonResponse(
                    {
                        "success": True,
                        "message": "Book availability toggled successfully.",
                    }
                )
            except Book.DoesNotExist:
                return JsonResponse({"success": False, "message": "Book not found."})
    return JsonResponse(
        {"success": False, "message": "Invalid request method or missing parameters."}
    )


def home(request):
    return render(request, "bookshelf/home.html")


def about(request):
    return render(request, "bookshelf/about.html")


def home(request):
    theme = request.session.get(
        "theme", "light"
    )  # Default to light theme if theme is not set
    return render(request, "bookshelf/home.html", {"theme": theme})

mindful_bookshelf/bookshelf/templates/bookshelf/about.html
{% extends 'bookshelf/base.html' %}

{% block title %}About - MindfulBookshelf{% endblock %}

{% block content %}
    <h1>About MindfulBookshelf</h1>
    <p>Welcome to MindfulBookshelf, your online bookstore for exploring a diverse collection of books on various topics. We believe in the power of literature to inspire, educate, and transform lives.</p>
    <p>At MindfulBookshelf, we are passionate about curating a selection of books that cater to different interests, from fiction and non-fiction to self-help and academic literature.</p>
    <p>Our mission is to promote a culture of reading and lifelong learning by providing access to high-quality books that enrich the mind and nourish the soul.</p>
    <p>Thank you for joining us on this journey of exploration and discovery. Happy reading!</p>
{% endblock %}

mindful_bookshelf/bookshelf/templates/bookshelf/add_book.html
{% extends 'bookshelf/base.html' %}
{% load static %}
{% block title %}Add New Book{% endblock %}
{% block content %}
    <h1>Add book</h1>
    <form enctype="multipart/form-data" method="post" id="book_form" novalidate>
        {% csrf_token %}
        <!-- Title -->
        <div class="form-row field-title">
            <label for="id_title">Title:</label>
            <input type="text" name="title" id="id_title" required>
        </div>
        <!-- Author -->
        <div class="form-row field-author">
            <label for="id_author">Author:</label>
            <input type="text" name="author" id="id_author" required>
        </div>
        <!-- Description -->
        <div class="form-row field-description">
            <label for="id_description">Description:</label>
            <textarea name="description" id="id_description" cols="40" rows="10" required></textarea>
        </div>
        <!-- Publication Date -->
        <div class="form-row field-publication_date">
            <div class="flex-container">
                <label class="required" for="id_publication_date">Publication date:</label>
                <p class="date">
                    <input type="text"
                           name="publication_date"
                           class="vDateField"
                           size="10"
                           required
                           id="id_publication_date"
                           maxlength="10"
                           autocomplete="off">
                </p>
                <p class="instructions">Please enter the publication date in the format YYYYMMDD (e.g., 20240307).</p>
            </div>
        </div>
        <!-- Category -->
        <div class="form-row field-category">
            <label for="id_category">Category:</label>
            <select name="category" id="id_category" required>
                <option value="" selected>---------</option>
            </select>
        </div>
        <!-- Cover Image -->
        <div class="form-row field-cover_image">
            <label for="id_cover_image">Cover image:</label>
            <input type="file" name="cover_image" id="id_cover_image" accept="image/*">
        </div>
        <!-- PDF Document -->
        <div class="form-row field-pdf_document">
            <label for="id_pdf_document">Pdf document:</label>
            <input type="file" name="pdf_document" id="id_pdf_document">
        </div>
        <div class="submit-row">
            <input type="submit" value="Save">
            <input type="submit" value="Save and add another" name="_addanother">
            <input type="submit" value="Save and continue editing" name="_continue">
        </div>
    </form>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            console.log('DOMContentLoaded event fired.');
            
            var inputField = document.getElementById('id_publication_date');
    
            inputField.addEventListener('input', function() {
                var value = inputField.value.replace(/\D/g, ''); // Remove non-numeric characters
                var formattedValue = '';
    
                if (value.length >= 4) {
                    formattedValue += value.substr(0, 4);
                }
                if (value.length >= 6) {
                    formattedValue += '-' + value.substr(4, 2);
                }
                if (value.length >= 8) {
                    formattedValue += '-' + value.substr(6, 2);
                }
    
                inputField.value = formattedValue;
            });

            // Fetch categories from backend
            fetch('/api/categories/')
                .then(response => response.json())
                .then(data => {
                    const categorySelect = document.getElementById('id_category');
                    data.forEach(category => {
                        const option = document.createElement('option');
                        option.value = category.id;
                        option.textContent = category.name;
                        categorySelect.appendChild(option);
                    });
                })
                .catch(error => console.error('Error fetching categories:', error));
        });
    </script>
{% endblock %}

mindful_bookshelf/bookshelf/templates/bookshelf/admin_overview.html
{% extends 'bookshelf/base.html' %}
{% load static %}
{% block title %}Admin Overview{% endblock %}
{% block content %}
    <div class="admin-overview">
        <h2>Add New Book</h2>
        <button id="addNewBook">Add New Book</button>
        <h2>Add New Category</h2>
        <a href="{% url 'add_category' %}" target="_blank">Add New Category</a>
        <h2>Books</h2>
        <input type="text" id="bookSearch" placeholder="Search Books">
        <select id="bookDropdown">
            <option value="" selected>Select Book</option>
            {% for book in books %}
                <option value="{{ book.id }}" data-available="{{ book.available }}">{{ book.title }}</option>
            {% endfor %}
        </select>
        <button id="showBookDetails"
                data-book-details-url="{% url 'book_detail' book_id=0 %}">Show Book Details</button>
        <h2>Users</h2>
        <div>
            {% if users %}
                <input type="text" id="userSearch" placeholder="Search Users">
                <select id="userDropdown">
                    <option value="" selected>Select User</option>
                    {% for user in users %}<option value="{{ user.id }}">{{ user.username }}</option>{% endfor %}
                </select>
                <button id="showUserDetails">Show User Details</button>
            {% else %}
                <p>No users available.</p>
            {% endif %}
        </div>
    </div>
    <div id="user-details-placeholder"></div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var bookDropdown = document.getElementById('bookDropdown');
            var bookSearchInput = document.getElementById('bookSearch');
            var userDropdown = document.getElementById('userDropdown');
            var userSearch = document.getElementById('userSearch');
            
            var bookDetailsUrl = document.getElementById('showBookDetails').getAttribute('data-book-details-url');
            var addNewBookButton = document.getElementById('addNewBook');

            // Filter book dropdown based on search input
            bookSearchInput.addEventListener('input', function() {
                var searchTerm = this.value.toLowerCase();
                var options = bookDropdown.options;
                var foundMatch = false;

                for (var i = 1; i < options.length; i++) {
                    var bookTitle = options[i].text.toLowerCase();
                    if (bookTitle.includes(searchTerm)) {
                        options[i].style.display = "block";
                        bookDropdown.selectedIndex = i; // Autofill with first matching book
                        foundMatch = true;
                        break; // Stop after finding the first match
                    } else {
                        options[i].style.display = "none";
                    }
                }
                if (!foundMatch) {
                    bookDropdown.selectedIndex = 0; // Reset to "Select Book"
                    alert("Book not found."); // Notify user if no match found
                } else {
                    // Trigger change event to simulate user selection
                    bookDropdown.dispatchEvent(new Event('change'));
                }
            });

            // Handle show book details button click
            document.getElementById('showBookDetails').addEventListener('click', function() {
                var selectedBookId = bookDropdown.value;
                if (selectedBookId) {
                    var url = bookDetailsUrl.replace('0', selectedBookId);
                    window.open(url, '_popup', 'width=800,height=600');
                } else {
                    alert("Please select a book.");
                }
            });

            // Filter user dropdown based on search input
            userSearch.addEventListener('input', function() {
                var searchTerm = this.value.toLowerCase();
                var options = userDropdown.options;

                for (var i = 1; i < options.length; i++) {
                    var username = options[i].text.toLowerCase();
                    if (username.startsWith(searchTerm)) {
                        options[i].style.display = "block";
                        userDropdown.selectedIndex = i; // Autofill with first matching user
                        return; // Stop after finding the first match
                    } else {
                        options[i].style.display = "none";
                    }
                }

                // If no match found, reset to "Select User"
                userDropdown.selectedIndex = 0;
            });

            // Handle search button click for users (optional)
            document.getElementById('showUserDetails').addEventListener('click', function() {
                var selectedUserId = userDropdown.value;
                if (selectedUserId) {
                    var url = "{% url 'user_details' %}?id=" + selectedUserId;
                    window.open(url, '_popup', 'width=600,height=400');
                } else {
                    alert("Please select a user.");
                }
            });

        // Handle add new book button click
        addNewBookButton.addEventListener('click', function() {
            var url = "{% url 'add_book' %}";
            // Define the size and attributes of the new window
            var newWindow = window.open(url, '_blank', 'width=800,height=600,top=100,left=100');
            // Focus on the new window
            newWindow.focus();
        });

            // ... other existing functions ...
        });
    </script>
{% endblock %}

mindful_bookshelf/bookshelf/templates/bookshelf/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}MindfulBookshelf{% endblock %}
        </title>
        <meta name="description"
              content="Explore a collection of books on various topics.">
        <meta name="keywords" content="books, literature, reading, bookshelf">
        <link rel="stylesheet" href="{% static 'bookshelf/css/global.css' %}">
        {% block extra_css %}{% endblock %}
    </head>
    <body>
        {% include 'bookshelf/header.html' %}
        <div class="content">
            {% block content %}{% endblock %}
        </div>
        {% include 'bookshelf/footer.html' %}
    </body>
</html>

mindful_bookshelf/bookshelf/templates/bookshelf/book_detail.html
{% load static %}
{% block title %}Book Details - {{ book.title }}{% endblock %}
{% block content %}
    <h1>{{ book.title }}</h1>
    <p>
        <strong>Author:</strong> {{ book.author }}
    </p>
    <p>
        <strong>Description:</strong> {{ book.description }}
    </p>
    <p>
        <strong>Publication Date:</strong> {{ book.publication_date|date:"F d, Y" }}
    </p>
    <p>
        <strong>Category:</strong> {{ book.category.name }}
    </p>
    {% if book.cover_image %}
        <img src="{{ book.cover_image.url }}"
             alt="Book Cover"
             width="200"
             height="300">
    {% else %}
        <p>No cover image available</p>
    {% endif %}
    <p>
        {% if book.pdf_document %}
            <a href="{% url 'book_detail' book_id=book.id %}">Read Book</a>
        {% else %}
            <p>No PDF available for this book</p>
        {% endif %}
    </p>
    {% if book.available %}
        <p>
            Status: <strong>Online</strong>
        </p>
    {% else %}
        <p>
            Status: <strong>Offline</strong>
        </p>
        <button id="toggleBookAvailability"
                data-book-id="{{ book.id }}"
                data-available="{{ book.available }}">Toggle Availability</button>
    {% endif %}
    {% if not book.available %}<button id="deleteBook" data-book-id="{{ book.id }}">Delete Book</button>{% endif %}
    <button id="editBookButton"
            data-book-id="{{ book.id }}"
            onclick="navigateToEditBook({{ book.id }})">Edit Book Details</button>
    <script>
                function navigateToEditBook(bookId) {
                  // Your JavaScript code to handle navigation (e.g., confirm popup, window.location)
                  window.location.href = "{% url 'edit_book' book_id=book.id %}"; // Example using window.location
                }
    </script>
{% endblock %}

mindful_bookshelf/bookshelf/templates/bookshelf/book_list.html
<!-- book_list.html -->
{% extends 'bookshelf/base.html' %}
{% block content %}
    <h1>Book List</h1>
    <ul>
        {% for book in books %}
            <li><a href="{% url 'book_detail' book.id %}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

mindful_bookshelf/bookshelf/templates/bookshelf/edit_book.html
{% block title %}Edit Book{% endblock %}
{% block content %}
    <h2>Edit Book</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- Render each form field individually -->
        <p>
            <label for="id_title">Title:</label>
            {{ form.title }}
        </p>
        <p>
            <label for="id_author">Author:</label>
            {{ form.author }}
        </p>
        <p>
            <label for="id_description">Description:</label>
            {{ form.description }}
        </p>
        <p>
            <label for="id_publication_date">Publication Date:</label>
            <input type="date"
                   name="publication_date"
                   required
                   id="id_publication_date"
                   value="{{ book.publication_date }}">
        </p>
        <p>
            <label for="id_picture">Picture:</label>
            <input type="file" name="picture" id="id_picture">
            {% if book.picture %}
                <img src="{{ book.picture.url }}"
                     alt="Book Cover"
                     width="200"
                     height="300">
            {% else %}
                <p>No picture available</p>
            {% endif %}
        </p>
        <p>
            <label for="id_pdf_document">PDF Document:</label>
            {{ form.pdf_document }}
        </p>
        <!-- Dropdown menu for selecting existing categories -->
        <p>
            <label for="id_category">Category:</label>
            <select name="category"
                    required
                    id="id_category"
                    onchange="toggleNewCategoryInput()">
                <option value="" selected>---------</option>
                {% for category in categories %}
                    <option value="{{ category.id }}"
                            {% if book.category == category %}selected{% endif %}>{{ category.name }}</option>
                {% endfor %}
                <!-- Option for adding a new category -->
                <option value="new">Add New Category</option>
            </select>
        </p>
        <!-- Input field for adding a new category -->
        <p id="new_category_input" style="display: none;">
            <label for="id_new_category_name">New Category Name:</label>
            <input type="text" name="new_category_name" id="id_new_category_name">
            <button type="submit">Add Category</button>
        </p>
        <button type="submit">Save Changes</button>
    </form>
    <script>
        function toggleNewCategoryInput() {
            var categorySelect = document.getElementById("id_category");
            var newCategoryInput = document.getElementById("new_category_input");

            if (categorySelect.value === "new") {
                categorySelect.style.display = "none";
                newCategoryInput.style.display = "block";
            } else {
                categorySelect.style.display = "block";
                newCategoryInput.style.display = "none";
            }
        }
    </script>
{% endblock %}

mindful_bookshelf/bookshelf/templates/bookshelf/footer.html
<footer>
    <p>© 2024 MindfulBookshelf</p>
</footer>

mindful_bookshelf/bookshelf/templates/bookshelf/header.html
<!-- header.html -->
{% load static %}
<header class="header">
    <!-- Logo -->
    <a href="{% url 'home' %}">
        <img src="{% static 'bookshelf/img/logos/Bookstore_light-removebg-preview.png' %}"
             alt="MindfulBookshelf Logo"
             class="logo logo-light"
             width="250"
             height="250">
    </a>
    <!-- Navigation -->
    <nav class="navigation">
        <ul>
            <li>
                <a href="{% url 'home' %}">Home</a>
            </li>
            <li>
                <a href="{% url 'book_list' %}">Books</a>
            </li>
            <li>
                <a href="{% url 'about' %}">About</a>
            </li>
            {% if user.is_authenticated %}
                {% if user.is_staff %}
                    <!-- Display admin overview link only for admin users -->
                    <li>
                        <a href="{% url 'admin_overview' %}">Admin Overview</a>
                    </li>
                {% endif %}
                <!-- Display sign-out link for authenticated users -->
                <li>
                    <a href="{% url 'logout' %}">Sign Out</a>
                </li>
            {% else %}
                <!-- Display sign-in link for non-authenticated users -->
                <li>
                    <a href="{% url 'login' %}">Sign In</a>
                </li>
                <!-- Display sign-up link for non-authenticated users -->
                <li>
                    <a href="{% url 'signup' %}">Sign Up</a>
                </li>
            {% endif %}
        </ul>
    </nav>
</header>

mindful_bookshelf/bookshelf/templates/bookshelf/signup.html
{% extends 'bookshelf/base.html' %}

{% block title %}Sign Up - My Bookshelf{% endblock %}

{% block content %}
<div class="signup-container">
    <h2>Sign Up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign Up</button>
    </form>
</div>
{% endblock %}